version: '3.8'

services:
  keeper:
    image: clickhouse/clickhouse-keeper:latest
    container_name: keeper
    ports:
      - "9181:9181"
    volumes:
      - ./keeper_server_config.xml:/etc/clickhouse-keeper/keeper_config.xml:ro

  ch-server-1:
    image: clickhouse/clickhouse-server:latest
    container_name: ch-server-1
    depends_on:
      - keeper
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_PASSWORD=123
    volumes:
      - ./keeper_client_config.xml:/etc/clickhouse-server/config.d/zookeeper.xml:ro
      - ./macros_server_1.xml:/etc/clickhouse-server/config.d/macros.xml:ro

  ch-server-2:
    image: clickhouse/clickhouse-server:latest
    container_name: ch-server-2
    depends_on:
      - keeper
    ports:
      - "8124:8123"
      - "9001:9000"
    environment:
      - CLICKHOUSE_PASSWORD=123
    volumes:
      - ./keeper_client_config.xml:/etc/clickhouse-server/config.d/zookeeper.xml:ro
      - ./macros_server_2.xml:/etc/clickhouse-server/config.d/macros.xml:ro